version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bram-backend
    ports:
      - ${FASTAPI_PORT}:8000
    volumes:
      - ./:/workspace
      - $HOME/.ssh:/root/.ssh
